name: deploy-container

on: 
  push:
    branches:
      - master
    paths:
      - 'packages/container/**'
  workflow_dispatch:
  
defaults:
  run:
    working-directory: packages/container
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
        env:
          GCP_SERVICE_ACCOUNT_KEY_FILE: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_FILE }}
          GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
          SOURCE_DIR: "public"
      - run: gsutil rsync -d -r dist gs://${{ secrets.GCP_BUCKET_NAME }}/data
